// [automatic generated by intermodule checker (imc) -- do not change ]
// 2018/01/24 17:04:25

#include "PearlIncludes.h" 



namespace pearlrt {
   int createSystemElements();
}

// enshure that the static (parametrized) objects are instanciated first
static int dummy = pearlrt::createSystemElements();

pearlrt::Device * d_stdout;	// systemtest2.prl:6
pearlrt::Device * d_stdin;	// systemtest2.prl:7
pearlrt::Device * d_lichtrechen;	// systemtest2.prl:8
pearlrt::Device * d_leftstepmotor_out;	// systemtest2.prl:9
pearlrt::Device * d_rightstepmotor_out;	// systemtest2.prl:10
pearlrt::Device * d_httpSocket;	// systemtest2.prl:11
pearlrt::Device * d_left_blinker;	// systemtest2.prl:12
pearlrt::Device * d_right_blinker;	// systemtest2.prl:13
pearlrt::Device * d_std_lights;	// systemtest2.prl:14
pearlrt::Device * d_stop_lights;	// systemtest2.prl:15
pearlrt::Device * d_farbsensor;	// systemtest2.prl:17



namespace pearlrt {
   int createSystemElements() {

	// systemtest2.prl:6
	static pearlrt::StdOut s_stdout;
	d_stdout = &s_stdout;

	// systemtest2.prl:7
	static pearlrt::StdIn s_stdin;
	d_stdin = &s_stdin;

	// systemtest2.prl:8
	static pearlrt::RPiDigitalIn s_lichtrechen(13, 8, (char*)"u");
	d_lichtrechen = &s_lichtrechen;

	// systemtest2.prl:9
	static pearlrt::RPiDigitalOut s_leftstepmotor_out(19, 4);
	d_leftstepmotor_out = &s_leftstepmotor_out;

	// systemtest2.prl:10
	static pearlrt::RPiDigitalOut s_rightstepmotor_out(23, 4);
	d_rightstepmotor_out = &s_rightstepmotor_out;

	// systemtest2.prl:11
	static pearlrt::TcpIpServer s_httpSocket(80);
	d_httpSocket = &s_httpSocket;

	// systemtest2.prl:12
	static pearlrt::RPiDigitalOut s_left_blinker(25, 1);
	d_left_blinker = &s_left_blinker;

	// systemtest2.prl:13
	static pearlrt::RPiDigitalOut s_right_blinker(24, 1);
	d_right_blinker = &s_right_blinker;

	// systemtest2.prl:14
	static pearlrt::RPiDigitalOut s_std_lights(26, 1);
	d_std_lights = &s_std_lights;

	// systemtest2.prl:15
	static pearlrt::RPiDigitalOut s_stop_lights(27, 1);
	d_stop_lights = &s_stop_lights;

	// systemtest2.prl:16
	static pearlrt::I2CBus s_i2cbus((char*)"/dev/i2c-1");

	// systemtest2.prl:17
	static pearlrt::TCS34725 s_farbsensor(& s_i2cbus, 0x29);
	d_farbsensor = &s_farbsensor;

   return 0;
   }
}
