// [automatic generated by intermodule checker (imc) -- do not change ]
// 2018/01/08 13:48:58

#include "PearlIncludes.h" 



namespace pearlrt {
   int createSystemElements();
}

// enshure that the static (parametrized) objects are instanciated first
static int dummy = pearlrt::createSystemElements();

pearlrt::Device * d_httpSocket;	// TestSocket.prl:4
pearlrt::Device * d_stdout;	// TestSocket.prl:5
pearlrt::Device * d_stdin;	// TestSocket.prl:6



namespace pearlrt {
   int createSystemElements() {

	// TestSocket.prl:4
	static pearlrt::TcpIpServer s_httpSocket(80);
	d_httpSocket = &s_httpSocket;

	// TestSocket.prl:5
	static pearlrt::StdOut s_stdout;
	d_stdout = &s_stdout;

	// TestSocket.prl:6
	static pearlrt::StdIn s_stdin;
	d_stdin = &s_stdin;

   return 0;
   }
}
